export default function About() {
  return (
    <div style={{ padding: '2rem', fontFamily: 'sans-serif' }}>
      <h1>ℹ️ About Page</h1>
      <p>यो /about route हो — auto-generated by dolphin-routing!</p>
      <a href="/">← Home</a>
    </div>
  );
}
