// 🐬 Auto-generated by DolphinCSS dolphin-routing
// ⚠️  DO NOT EDIT — changes will be overwritten on next save
// Add/remove pages in src/pages/ to update routes

import { lazy, Suspense } from 'react';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';


const Route0 = lazy(() => import('./pages/about.jsx'));
const Route1 = lazy(() => import('./pages/blog/index.jsx'));
const Route2 = lazy(() => import('./pages/blog/[slug].jsx'));
const Route3 = lazy(() => import('./pages/index.jsx'));

const router = createBrowserRouter([
  { path: '/about', element: <Route0 /> },
  { path: '/blog', element: <Route1 /> },
  { path: '/blog/:slug', element: <Route2 /> },
  { path: '/', element: <Route3 /> }
]);

export default function AppRouter() {
  return (
    <Suspense fallback={<div>
<div className="flex flex-col items-center justify-center gap-4 p-8 fx-crystal rounded-3xl max-w-sm mx-auto bg-surface/40">
  <div className="loader-dolphin-jump">
    <div className="dolphin"></div>
    <div className="wave"></div>
  </div>
  <p className="text-sm font-semibold text-text-muted animate-pulse tracking-wide">Loading...</p>
</div>

</Suspense>
  );
}
